// <auto-generated />
using System;
using LabCourse2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabCourse2.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608230222_SyncDatabaseModel")]
    partial class SyncDatabaseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabCourse2.Domain.Entities.Audit_Logs", b =>
                {
                    b.Property<Guid>("Audit_LogsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<int>("IPaddress")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("new_values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("old_values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Audit_LogsID");

                    b.HasIndex("UserID");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ClientProfile", b =>
                {
                    b.Property<Guid>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Agreed_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreelancerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProposalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractID");

                    b.HasIndex("ClientID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("ProposalID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FreelancerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConversationID");

                    b.HasIndex("ClientID");

                    b.HasIndex("ContractID");

                    b.HasIndex("FreelancerID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Deliverables", b =>
                {
                    b.Property<Guid>("DeliverablesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Approved_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MilestoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Submitted_at")
                        .HasColumnType("datetime2");

                    b.HasKey("DeliverablesID");

                    b.HasIndex("FileID");

                    b.HasIndex("MilestoneID");

                    b.ToTable("Deliverables");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Favorite_Freelancer", b =>
                {
                    b.Property<Guid>("Favorite_FreelancerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FreelancerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Favorite_FreelancerID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("ClientID", "FreelancerID")
                        .IsUnique();

                    b.ToTable("Favorite_Freelancers");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Files", b =>
                {
                    b.Property<Guid>("FilesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("File_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("File_Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uploaded_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilesID");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.FreelancerProfile", b =>
                {
                    b.Property<Guid>("FreelancerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Experience_Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hourly_Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("StripePayoutsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FreelancerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("FreelancerProfiles");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.FreelancerSkills", b =>
                {
                    b.Property<Guid>("FreelancerSkillsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FreelancerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SkillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FreelancerSkillsID");

                    b.HasIndex("FreelancerID");

                    b.HasIndex("SkillID");

                    b.ToTable("FreelancerSkills");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("SenderUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Sent_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MessageID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("SenderUserID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Milestone", b =>
                {
                    b.Property<Guid>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Approved_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Funded_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order_Index")
                        .HasColumnType("int");

                    b.Property<string>("Submission_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Submitted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MilestoneID");

                    b.HasIndex("ContractID");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("MilestoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StripeChargeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeTransferId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentID");

                    b.HasIndex("ContractID");

                    b.HasIndex("MilestoneID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionsID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionsID = new Guid("d4e5f6a7-b8c9-4d5e-8f9a-3b4c5d6e7f8a"),
                            Description = "Permission to create and post new projects",
                            Name = "projects.create"
                        },
                        new
                        {
                            PermissionsID = new Guid("e5f6a7b8-c9da-4e5f-8a9b-4c5d6e7f8a9b"),
                            Description = "Permission to delete projects",
                            Name = "projects.delete"
                        },
                        new
                        {
                            PermissionsID = new Guid("f6a7b8c9-daeb-4f5a-8b9c-5d6e7f8a9b0c"),
                            Description = "Permission to submit proposals for projects",
                            Name = "proposals.submit"
                        },
                        new
                        {
                            PermissionsID = new Guid("a7b8c9da-ebfc-4a5b-8c9d-6e7f8a9b0c1d"),
                            Description = "Permission to block or suspend user accounts",
                            Name = "users.block"
                        });
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ProcessedStripeEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedStripeEvents");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ClientID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ProjectSkills", b =>
                {
                    b.Property<Guid>("ProjectSkillsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjectSkillsID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("SkillID");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Proposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("int");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProposalId");

                    b.HasIndex("FreelancerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Protected_Views", b =>
                {
                    b.Property<Guid>("Protected_ViewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Viewed_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Protected_ViewsID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Protected_Views");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedFromIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Revoked_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportsID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreelancerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewsID");

                    b.HasIndex("ClientID");

                    b.HasIndex("ContractID");

                    b.HasIndex("FreelancerID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full system access and management capabilities",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("b2c3d4e5-f6a7-4b5c-8d9e-1f2a3b4c5d6e"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role for project owners who create projects and hire freelancers",
                            Name = "Client"
                        },
                        new
                        {
                            RoleID = new Guid("c3d4e5f6-a7b8-4c5d-8e9f-2a3b4c5d6e7f"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Role for independent service providers who submit proposals and complete projects",
                            Name = "Freelancer"
                        });
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolePermissionsID");

                    b.HasIndex("PermissionsID");

                    b.HasIndex("RoleID", "PermissionsID")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionsID = new Guid("d1e2f3a4-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("d4e5f6a7-b8c9-4d5e-8f9a-3b4c5d6e7f8a"),
                            RoleID = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RolePermissionsID = new Guid("e2f3a4b5-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("e5f6a7b8-c9da-4e5f-8a9b-4c5d6e7f8a9b"),
                            RoleID = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RolePermissionsID = new Guid("f3a4b5c6-d7e8-4f9a-0b1c-2d3e4f5a6b7c"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("f6a7b8c9-daeb-4f5a-8b9c-5d6e7f8a9b0c"),
                            RoleID = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RolePermissionsID = new Guid("a4b5c6d7-e8f9-4a0b-1c2d-3e4f5a6b7c8d"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("a7b8c9da-ebfc-4a5b-8c9d-6e7f8a9b0c1d"),
                            RoleID = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d")
                        },
                        new
                        {
                            RolePermissionsID = new Guid("b5c6d7e8-f9a0-4b1c-2d3e-4f5a6b7c8d9e"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("d4e5f6a7-b8c9-4d5e-8f9a-3b4c5d6e7f8a"),
                            RoleID = new Guid("b2c3d4e5-f6a7-4b5c-8d9e-1f2a3b4c5d6e")
                        },
                        new
                        {
                            RolePermissionsID = new Guid("c6d7e8f9-a0b1-4c2d-3e4f-5a6b7c8d9e0f"),
                            Created_At = new DateTime(2025, 4, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            PermissionsID = new Guid("f6a7b8c9-daeb-4f5a-8b9c-5d6e7f8a9b0c"),
                            RoleID = new Guid("c3d4e5f6-a7b8-4c5d-8e9f-2a3b4c5d6e7f")
                        });
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.SavedProjects", b =>
                {
                    b.Property<Guid>("SavedProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SavedProjectID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedProjects");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Skills", b =>
                {
                    b.Property<Guid>("SkillsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillsID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Transactions", b =>
                {
                    b.Property<Guid>("TransactionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MilestoneID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionsID");

                    b.HasIndex("MilestoneID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Type", "[Type] IN ('deposit','release','refund')");
                        });
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile_Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRolesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Assigned_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRolesID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID", "RoleID")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Audit_Logs", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ClientProfile", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("LabCourse2.Domain.Entities.ClientProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Contract", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.ClientProfile", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany("Contracts")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Project", "Project")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Proposal", "Proposal")
                        .WithMany()
                        .HasForeignKey("ProposalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Freelancer");

                    b.Navigation("Project");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.ClientProfile", "Client")
                        .WithMany("Conversations")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany("Conversations")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contract");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Deliverables", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Files", "File")
                        .WithMany()
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Milestone", "Milestone")
                        .WithMany("Deliverables")
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Favorite_Freelancer", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.ClientProfile", "Client")
                        .WithMany("FavoriteFreelancers")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany("FavoriteFreelancers")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.FreelancerProfile", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithOne("FreelancerProfile")
                        .HasForeignKey("LabCourse2.Domain.Entities.FreelancerProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.FreelancerSkills", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany()
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Skills", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Message", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.User", "SenderUser")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Milestone", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Contract", "Contract")
                        .WithMany("Milestones")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Notification", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Payment", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Contract", null)
                        .WithMany("Payment")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Project", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.ClientProfile", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ProjectSkills", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Skills", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Proposal", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Freelancer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Protected_Views", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Project", "Project")
                        .WithMany("ProtetectedViews")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("ProtectedViews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Report", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Review", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.ClientProfile", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Contract", "Contract")
                        .WithMany("Reviews")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.FreelancerProfile", "Freelancer")
                        .WithMany("Reviews")
                        .HasForeignKey("FreelancerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contract");

                    b.Navigation("Freelancer");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.SavedProjects", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Transactions", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Milestone", "Milestone")
                        .WithMany("Transactions")
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("LabCourse2.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCourse2.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.ClientProfile", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Conversations");

                    b.Navigation("FavoriteFreelancers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.FreelancerProfile", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Conversations");

                    b.Navigation("FavoriteFreelancers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Milestone", b =>
                {
                    b.Navigation("Deliverables");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Project", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("ProtetectedViews");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LabCourse2.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ClientProfile");

                    b.Navigation("FreelancerProfile");

                    b.Navigation("MessagesSent");

                    b.Navigation("Notifications");

                    b.Navigation("ProtectedViews");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
